language: bash
before_deploy:
  - zip -rq cxf-${TRAVIS_BUILD_NUMBER} .
  - echo "Zip source files to release"
  - test -d dpl_cd_upload || mkdir dpl_cd_upload
  - mv cxf-${TRAVIS_BUILD_NUMBER}.zip dpl_cd_upload/cxf-${TRAVIS_BUILD_NUMBER}.zip
  - echo "Move zipped file to upload folder"
deploy:
# dev
  - provider: s3
    detect_encoding: true
    access_key_id: $AWS_ACCESS_KEY_DEV
    secret_access_key: $AWS_SECRET_KEY_DEV
    local_dir: dpl_cd_upload
    skip_cleanup: true
    region: ap-northeast-1
    bucket: hrm-java-test
    on:
      branch: lab
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY_DEV
    secret_access_key: $AWS_SECRET_KEY_DEV
    region: ap-northeast-1
    bucket: hrm-java-test
    key: cxf-${TRAVIS_BUILD_NUMBER}.zip
    bundle_type: zip
    application: cd-104pro-cxf
    deployment_group: cd-104pro-cxf
    wait-until-deployed: true
    on:
      branch: lab
